sudo: false
language: node_js
node_js:
- "0.10"
branches:
  only:
  - master
  - develop
env:
  global:
    # GPG_KEY
    - secure: "M02b7iC88rHJ11gOFRtsAo/Y6lq3qkRskiPmE19YMk+BiX9NVt5XdUgwP/3X7XyQN0PSxuDKGP7HIsOKE4R7uukLB+dLDCBXWVYFTUWeCwggXOK+eJ23pQ6WXJDCKJJiHwjz2vtxXjO28vyP1a2MQsZ9jSPs5XIQNBvJg9fwpcI="
before_install:
- npm install -g grunt-cli
- npm install -g bower
- bower install
script: grunt
after_script: bash travis.sh